### PR TITLE
SRCH-5548 filtering by path

### PR DESCRIPTION
**Pull request by selfdanielj**
## Summary
* Goal here is to add ability to filter links we find by the url path.  I accomplished this by extending the built in offsite middleware which in addition to the domain checking adds this ability.  There are some examples in the JIRA story but simply if an `allowed_domains` value contains a path, e.g. `quotes.toscrape.com/tag/` the the spider will only output links from that domain that contain the path `tag`.
* Changes of Note:
  * New middleware to accomplish the filtering as well as enabling the middleware in settings.
  * Updates the helper methods to allow for creation of new argument to spider to contain domains with paths separate from just the domains.  This helped to ensure that we didnt mess with the exsting domain limiting functionality.
  * Moved `parse_item` back to the spiders to help with using built in scrapy CLI tools to test and debug.
  * Updated plist conversion script with filters and addition of paths where appropriate.
  * Removed three entries from crawl list and added path filters per Jim's instructions
  * Updated init schedule sql (will clean up during init automation story).
  * Updated tests and httpcache for tests
  * Added additional tests where needed.

Testing:
* Try things for yourself.  For example, compare output of the following two scrape commands:
  * `scrapy crawl domain_spider -a allowed_domains=quotes.toscrape.com -a start_urls=https://quotes.toscrape.com`
  * `scrapy crawl domain_spider -a allowed_domains=quotes.toscrape.com/tag/ -a start_urls=https://quotes.toscrape.com`
* Try with scrapyd
  *   `scrapyd-deploy local -p search_gov_spiders`
  *  `curl http://localhost:6800/schedule.json -d project=search_gov_spiders -d spider=domain_spider -d allowed_domains=quotes.toscrape.com/tag/ -d start_urls=https://quotes.toscrape.com`
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.

#### Functionality Checks

- [X] You have merged the latest changes from the target branch (usually `main`) into your branch.

- [X] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [X] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.

- [X] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:

#### Process Checks

- [X] You have specified at least one "Reviewer".

### CODE REVIEW

**Comment by IsabelLaurenceau** [comment]
I am able to test it correctly using scrapyd. When I try to just run the scrape commands though it's not writing the output to a csv file even though it says 

`{"asctime": "2024-10-07 14:12:46,476", "name": "scrapy.extensions.feedexport", "levelname": "INFO", "message": "Stored csv feed (120 items) in: scrapy_urls/domain_spider/domain_spider_2024-10-07T18-12-40+00-00.txt", "spider": "domain_spider"}`

I can see based on the console messages though it's returning the right number of items (120 for /tag and 378 for the entire domain). Is the not writing to a file intended now?

**Comment by selfdanielj** [comment]
> intended now?

it should still write to the CSV... ill take a look.

**Comment by selfdanielj** [comment]
> I am able to test it correctly using scrapyd. When I try to just run the scrape commands though it's not writing the output to a csv file even though it says
> 
> `{"asctime": "2024-10-07 14:12:46,476", "name": "scrapy.extensions.feedexport", "levelname": "INFO", "message": "Stored csv feed (120 items) in: scrapy_urls/domain_spider/domain_spider_2024-10-07T18-12-40+00-00.txt", "spider": "domain_spider"}`
> 
> I can see based on the console messages though it's returning the right number of items (120 for /tag and 378 for the entire domain). Is the not writing to a file intended now?

Seems to work for me... is this what you are doing?

```
(.venv) ➜  search_gov_spiders git:(SRCH-5548_filtering_by_path) pwd
/Users/dself/Projects/searchgov-spider/search_gov_crawler/search_gov_spiders
(.venv) ➜  search_gov_spiders git:(SRCH-5548_filtering_by_path) ls -la ../output
total 8
drwxr-xr-x   3 dself  staff   96 Oct  7 15:17 ./
drwxr-xr-x  23 dself  staff  736 Oct  7 14:51 ../
-rw-r--r--   1 dself  staff   70 Aug 22 09:36 .gitignore
(.venv) ➜  search_gov_spiders git:(SRCH-5548_filtering_by_path) scrapy crawl domain_spider -a allowed_domains=quotes.toscrape.com/tag/ -a start_urls=https://quotes.toscrape.com
... output from run ...
(.venv) ➜  search_gov_spiders git:(SRCH-5548_filtering_by_path) ls -la ../output
total 24
drwxr-xr-x   5 dself  staff   160 Oct  7 15:17 ./
drwxr-xr-x  23 dself  staff   736 Oct  7 14:51 ../
-rw-r--r--   1 dself  staff    70 Aug 22 09:36 .gitignore
-rw-r--r--   1 dself  staff  1948 Oct  7 15:17 all-links.csv
-rw-r--r--   1 dself  staff  3897 Oct  7 15:17 all-links1.csv
(.venv) ➜  search_gov_spiders git:(SRCH-5548_filtering_by_path) wc -l ../output/all-links.csv 
      40 ../output/all-links.csv
(.venv) ➜  search_gov_spiders git:(SRCH-5548_filtering_by_path) wc -l ../output/all-links1.csv
      80 ../output/all-links1.csv
```

**Comment by IsabelLaurenceau** [comment]
Ah okay. I am getting them in the output/all-links{x}.csv but based on the message I was also looking for them in scrapy_urls/domain_spider. I remember we discussed removing them from there but I didn't expect to see that message in the logs.

**Review by igoristic — APPROVED** [review]
Looks good! Nice work 🥇

**Pull request merged**
